### ISSUE TITLE
error again.

### ISSUE THREAD

**Issue by 5mf** [codeuk/TrollWare#5]
Hello! Sorry to bother you but i see you came with a fix and .. i get a new error. 
`Traceback (most recent call last):
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 1364, in <module>  
    start()
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 1356, in start     
    Logging.Discord.FetchTokens()
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 486, in FetchTokens
    billinginfo = Logging.Discord.GetBilling(token)
  File "C:\Users\andre\OneDrive\Desktop\TrollWare-main\main.py", line 347, in GetBilling  
    billingmail = response.json()[0]['email']
IndexError: list index out of range`

Any fix?

**Comment by codeuk** [comment]
I'm having some trouble with testing, I can't seem to generate this output; It's most likely something to do with your billing configuration *(maybe your Discord account doesn't have billing enabled? no email attached?)*

Please respond as I'm consfused on why you're getting this error *(tell me if you have no email, billing, etc.)*

**Comment by codeuk** [comment]
I've commited a fix for this issue, it is indeed due to your account not having billing on it. Go redownload the repo and try again.

**Comment by 5mf** [comment]
and do i just turn billing off? *from settings*
